### PR TITLE
Improvements/bug fixes for user project intellisense

### PR DESCRIPTION
**Pull request by andrewsdev**
Note: These have not been heavily tested, and I only have access to a Windows machine.  I am creating this pull request to hopefully avoid other people starting to work on these problems and needlessly duplicating work while I finalize my own testing over the next week.  I encourage you to absorb these changes locally and see what you think; it is especially critical that this be looked at on Linux and/or Mac.

Bug Fixes:
- If you have written a type signature before writing the function definition, you will now get the function's name in intellisense instead of "function definition not found"
- Fixed bug where the /as/ regex for the list of imports would incorrectly match on Task and cause an undefined error breaking all intellisense.  Note: Try/catch should probably be added so that if a completion item encounters an exception it does not nullify all results.
UPDATE: 
- Fixed bug where the name of a user's type or type alias were not included in intellisense results

Coding Changes:
- Moved the elm-package.json parsing further up in the userProject function (new functions called earlier need this information)
- changed the module name in the imports section (where the /as/ matching takes place) to only split once, and use that array for its name (position 1 or 3 as appropriate)

New Feature:
- Primitive types are now included in autocomplete when writing a function definition.  Only added Int, String, Bool, Float for now
Update:
- The arbitrary limit on user intellisense 'comment' size (elm.userProjectMaxCommentSize) now better indicates it has hit a settings limit
- Can now set elm.userProjectMaxCommentSize to 0 to bypass the limit

Major New Feature:
- Added the ability to get intellisense (hover and autocomplete) for user modules with a '.' in their names.  Ie Players.List and Players.Edit.  
- Added a new setting to control this.  By default it will replace the . in the name with the file separator (path.sep) and attempt to read that file name (ie, Players.List becomes src/Players/List.elm). _This may not be the most appropriate default_ depending on how projects are commonly structured.  This also perpetuates the current assumption that all Elm modules are named exactly the same as their file name.
-Alternate settings are dynamicLookup which will read the directory structure and parse the first few lines of all files (until it finds the module definition).  It uses this information to build an array with the true file path, and looks that up.  
- An alternative to this is semiDynamicLookup which only performs the directory scan once and keeps the array in memory.  It is possible that dynamicLookup will be prohibitively slow for large elm projects; I tested it with Richard Feldmen's SPA example and it was instant; the bottom line is I'm not sure.

### CODE REVIEW

**Comment by andrewsdev** [comment]
@hakonrossebo or @Krzysztof-Cieslak , do either of you use Linux/Mac? I'm satisfied with my local tests of this PR but because it deals in file paths it should be tested on non-windows before being merged.

If not I'll put out a call on Slack/Reddit

**Comment by hakonrossebo** [comment]
I can do a test with Linux now :)

**Comment by andrewsdev** [comment]
Thanks very much. I'll get a vmware going so I can test this myself next time.

Note that there is a bug I noticed which was not introduced by this PR where the names of your type and type alias are not included in intellisense results.  I have a fix queued up for this already and will add a PR once this one is merged, but if you see that in your tests, it's expected.

**Comment by hakonrossebo** [comment]
Testing on linux now -not sure if I get the same results on windows. Using the elm-spa-example, hovering over pageLoadError, I'm getting this information:
image

Am I supposed to get the function signature? Debugging the userProject, I'm getting this as a result from userProject

Array[11] [Object, Object, Object …]
where the first item is Object {name: "pageLoadError", fullName: "pageLoadError", signature: "pageLoadError" …} (comment is: <details>
"type Msg
    = DismissErrors
    | ToggleFavorite
    | FavoriteCompleted (Result Http.Error (Article Body))
    | ToggleFollow
    | FollowCompleted (Result Http.Error Author)
    | SetCommentText String
    | DeleteComment CommentId
    | CommentDeleted CommentId (Result Http.Error ())
    | PostComment
    | CommentPosted (Result Http.Error Comment)
    | DeleteArticle
...(more than 11 lines, see vscode-elm settings)

--/home/hakon/source/repos/elm-spa-example/src/Page/Article.elm"
</details>

item 3 has the correct signature Object {name: "pageLoadError", fullName: "pageLoadError activePage errorMessage ", signature: "pageLoadError : ActivePage -> String -> PageLoadEr…" …}

**Comment by hakonrossebo** [comment]
Anyways - file handling/paths seems to work fine on linux.

**Comment by andrewsdev** [comment]
Thanks for performing the test. This is definitely a bug you found: hover requests should only ever return 1 result. It is possible there is a type or type alias with the same name (but different case) as that function but even still, all hover matching should be case sensitive. 

This will be easy to replicate and correct later today

**Comment by andrewsdev** [comment]
Corrected.  I made some modifications to simplify how Type declarations were included in intellisense results but left off the condition that checked if your hover result was actually in the Type you hovered.  

This PR is now ready for final review/merging.

**Comment by hakonrossebo** [comment]
Tested and verified ok. Seems to work much better with the dynamicLookup import strategy, maybe you could use that as a default?

**Comment by andrewsdev** [comment]
I was thinking the same thing... It's the setting I've left my own environment on.  It has the potential to be a breaking change for people with incredibly large projects, but I can't quantify that because I don't have large Elm projects.  

I think we should set it to default and then on the next release maybe make a warning in the release notes.

**Comment by Krzysztof-Cieslak** [comment]
OK, this works well enough on my test projects. Great work! :)

**Comment by Krzysztof-Cieslak** [comment]
I'd also appreciate PR to readme describing new Intellisense behavior, and differences between import strategy.

**Pull request merged**
