### PR TITLE
Fix elm 19 commands

### PR DESCRIPTION
**Pull request by 7sharp9**
Have `elm` as the default command, add docs to the "elm.makeCommand" configuration with details on setting it to elm-make for versions prior to 0.19

Addresses elm-make in #242

### CODE REVIEW

**Comment by 7sharp9** [comment]
- [x] elm-make
- [ ] elm-reactor
- [ ] elm-repl
- [ ] elm-package

**Comment by lbighetti** [comment]
This is great! I believe this would be greatly beneficial to VSCode users even with just the `elm make` working properly. Would really like to see this merged!

**Comment by hakonrossebo** [comment]
I updated my branch with a new commit that contains code from @axelo to patch the new json report format into the existing structure. Please feel free to include it in this PR. https://github.com/Krzysztof-Cieslak/vscode-elm/commit/66bc692f8c31fec89bef5ff286f63a8cf597d666

**Comment by 7sharp9** [comment]
@hakonrossebo I can cherrypick that a bit later on.   Feel free to add to my PR too though

**Comment by hakonrossebo** [comment]
Added code to PR now. I can help with other commands if you intend to do the other commands in this PR - just give me a hint to what command to work on.

**Comment by 7sharp9** [comment]
ok, cool, I'll look at repl or reactor, tomorrow now though, work permitting :-)

**Comment by hakonrossebo** [comment]
Managed to finish package install and browsing. Seems like elm install does not have a --yes parameter. It gets stuck when displaying the confirmation in the output window.

**Comment by 7sharp9** [comment]
Elm make also lost the yes param too

**Comment by hakonrossebo** [comment]
Ok, I'll ask on elm-dev

**Comment by hakonrossebo** [comment]
I've added commits for Reactor and Repl. I can't see any output in vscode when starting Reactor, but it seems to work ok.

**Comment by 7sharp9** [comment]
Ok Ive just tested reactor and repl so all the commands that were broken seem to be fixed.  All that remains is the oracle stuff which which is probably better done in another PR as it will be more pervasive and probably take a lot longer, maybe we should disable those features for the time being and release this as is?   At least then people can use 0.19 with vscode

**Comment by 7sharp9** [comment]
@hakonrossebo repl seems to have some artifacts in the console:

screen shot 2018-08-24 at 09 45 52

**Comment by hakonrossebo** [comment]
I think we can release this PR as is and fix any issues later. Probably better for most people.

**Comment by Punie** [comment]
@hakonrossebo  you can add the `--no-colors` to the `elm repl` command. You'll still have those artefacts on the startup header of the repl though.

**Comment by 7sharp9** [comment]
I think if we are switching to using the terminal for the repl in the future this may disappear then.

**Pull request merged**
