### PR TITLE
added tslint dependency and run script

### PR DESCRIPTION
**Pull request by littleStudent**
I added a the tslint run script and dependency.
https://github.com/Krzysztof-Cieslak/vscode-elm/pull/145#discussion_r124191453

A tslint.json file was already present, so I kept that one.
I did not fix all the linter errors for now. Should I?

Do we want to add something like [prettier](https://github.com/prettier/prettier)?

### CODE REVIEW

**Comment by hakonrossebo** [comment]
This is great. Only answering for myself, but I think it's great if you want to fix all linter errors. I've only heard good things about prettier, and I think elm-format is a "must-have".

**Comment by littleStudent** [comment]
Alright I will go through the linting errors. (there are a bunch 😂)

For adding prettier I will create a new PR.

**Comment by hakonrossebo** [comment]
Ok, I guess we can help out with fixing the linting errors. We can fix these in separate pr's.

**Comment by littleStudent** [comment]
I fixed all the tslint errors.

**Comment by hakonrossebo** [comment]
Thanks, I'll try to verify the changes today.

**Comment by hakonrossebo** [comment]
Looking at the changes now. I'm not fully educated on Typescript versions. Until now, while working on the project, I've used Typescript 1.8.10 (in vscode statusbar) since this is the workspace version (package.json specifies Typescript1.6.2 and vscode 0.10.7 as devDependencies).

Running with 1.8.10 (in vscode statusbar) resulted in a few linting errors that went away when I chose Typescript 2.3.4. I've been hoping we could use/update to latest Typescript 2.3.4/vscode version, but have not gotten to verify/ask if we could update - Can we switch to 2.3.4 and latest vscode version?

I noticed rimraf had been removed from package.json. This also resulted in an error to start the plugin. This was resolved when I added rimraf via npm.

Other than that, code looks ok (a bit unfamiliar with linebreaks) and I think it's very good to finally have some linting on typescript syntax. Did you run prettier to enforce this linting?

@Krzysztof-Cieslak, @andrewsdev - Do you have any feedback on linting and Typescript/vscode versions?

**Comment by littleStudent** [comment]
I did not want to interfere with any typescript update, so I just went with the one that was configured. I can upgrade typescript and tslint if you want me to?

removing rimraf was not intentional 😱 . sorry for that.

prettier is not setup in this PR yet. Running prettier will change nearly every single line of code. Which may result in some nasty git-conflicts.
I think i ran it on the `elmCodeAction.ts` file because it auto-fixed nearly all linting errors.

I had in mind to add prettier in a new PR after this one is merged, but we could also add it to this PR?

**Comment by hakonrossebo** [comment]
Great if you could help with upgrading typescript and tslint. 

I think it's good to separate the updates and prettier implementation to separate PR's.

**Comment by hakonrossebo** [comment]
While we discuss Typescript. I've noticed that our project has tsconfig.json CompilerOptions.target: "es5", while a new vscode scaffold project uses es6. Should we update to es6?

**Comment by hakonrossebo** [comment]
Checked and verified latest changes - everything seems to work ok.

**Comment by Krzysztof-Cieslak** [comment]
Great, looks good to me :)

**Comment by hakonrossebo** [comment]
@littleStudent - I've updated one of my PR's to compile with the latest tslint and typescript updates. I seem to struggle as I'm not able to run the changes. I've also tried on the master branch - added some console.log + vscode.window.showInformationMessage on activation in main and in reactor start. The changes does not seem to take effect - can you verify if this works as expected on your machine?

**Comment by littleStudent** [comment]
So i have fixed a few things in this branch https://github.com/littleStudent/vscode-elm/tree/typescript-corrections.
Can you try it there again? adding `console.log` and `vscode.window.showInformationMessage` did both work for me there

**Comment by hakonrossebo** [comment]
As we have discussed on Slack - this seems to work fine for me now. Also seems to solve the issues for #145

**Pull request merged**
