### PR TITLE
style: lint the code and modify

### PR DESCRIPTION
**Pull request by monkingxue**
lint the code

### CODE REVIEW

**Comment by monkingxue** [comment]
Hi, I want to contribute to this repo, but how can I test the code?

**Comment by monkingxue** [comment]
@littleStudent Excuse me，but how can I test the project?
 I run the command `npm test` but it failed with an error `Error: Error: Cannot find module '/Users/xx/yy/vscode-elm/test'`

**Comment by milesfrain** [comment]
@monkingxue I'm not sure how to execute the .test.ts files located in the test/ directory, but for manual testing, I listed some of the steps in required to build and load the extension in #212 . We should add a "for developers" section in the readme with instructions on contributing once we figure out best practices.

**Comment by monkingxue** [comment]
@milesfrain Yeah, I find the many issues about feature-request and maybe we can fix it.

**Pull request closed without merging**
