### PR TITLE
Elm-reactor subdir traversal

### PR DESCRIPTION
**Pull request by hakonrossebo**
This allows specifying a traversal to a parent path and fixes issue #90

### CODE REVIEW

**Comment by Krzysztof-Cieslak** [comment]
@hakonrossebo, would you like to become one of the collaborators for the repository? You would have write access to repository, so you could commit small changes like this directly, without waiting for me to merge PR?

**Comment by hakonrossebo** [comment]
Thanks - I would appreciate that. Should I still always create PR's and merge the simpler ones like this myself?

**Comment by Krzysztof-Cieslak** [comment]
I've sent you invitation. 

>  Should I still always create PR's and merge the simpler ones like this myself?

Yeah, we can agree to do that, this will make tracking things for me bit easier :)

**Comment by hakonrossebo** [comment]
Thanks - should I merge this PR?

**Comment by Krzysztof-Cieslak** [comment]
Go ahead. :)

**Pull request merged**
